#!/bin/bash

./dell2.sh -out /home/jorge/exps/EC/pred/nsga_e13_group -p jobs=30 -p parent.0=build/classes/mase/app/pred/oneprey.params -p parent.1=build/classes/mase/novelty/nsga_ga.params -p parent.2=build/classes/mase/cooperative.params -p parent.3=build/classes/mase/gax.params -p pop.default-subpop.size=75 -p generations=500 -p pop.subpops=3 -p problem.escape-distance=13 -p eval.post.0.archive-size=2000 -p eval.post.0.archive-growth=0.025 -p eval.base.elite-mode=fitness

./dell2.sh -out /home/jorge/exps/EC/pred/nsga_e13_ind -p jobs=30 -p parent.0=build/classes/mase/app/pred/oneprey.params -p parent.1=build/classes/mase/novelty/nsga_ga.params -p parent.2=build/classes/mase/cooperative.params -p parent.3=build/classes/mase/gax.params -p pop.default-subpop.size=75 -p generations=500 -p pop.subpops=3 -p problem.escape-distance=13 -p fitness.novelty-index=2 -p eval.post.0.archive-mode=multiple -p eval.post.0.archive-size=2000 -p eval.post.0.archive-growth=0.025 -p eval.base.elite-mode=fitness

./dell2.sh -out /home/jorge/exps/EC/pred/nsga_e13_mix50 -p jobs=30 -p parent.0=build/classes/mase/app/pred/oneprey.params -p parent.1=build/classes/mase/novelty/nsga_ga.params -p parent.2=build/classes/mase/cooperative.params -p parent.3=build/classes/mase/gax.params -p pop.default-subpop.size=75 -p generations=500 -p pop.subpops=3 -p problem.escape-distance=13 -p fitness.novelty-index=2 -p eval.post.0.archive-mode=multiple -p eval.post.0.archive-size=2000 -p eval.post.0.archive-growth=0.025 -p eval.base.elite-mode=fitness -p eval.post.0=mase.novelty.GroupIndNoveltyEvaluation -p eval.post.0.group-behav-index=1 -p eval.post.0.group-weight=0.5

./dell2.sh -out /home/jorge/exps/EC/pred/nsga_e13_mix25 -p jobs=30 -p parent.0=build/classes/mase/app/pred/oneprey.params -p parent.1=build/classes/mase/novelty/nsga_ga.params -p parent.2=build/classes/mase/cooperative.params -p parent.3=build/classes/mase/gax.params -p pop.default-subpop.size=75 -p generations=500 -p pop.subpops=3 -p problem.escape-distance=13 -p fitness.novelty-index=2 -p eval.post.0.archive-mode=multiple -p eval.post.0.archive-size=2000 -p eval.post.0.archive-growth=0.025 -p eval.base.elite-mode=fitness -p eval.post.0=mase.novelty.GroupIndNoveltyEvaluation -p eval.post.0.group-behav-index=1 -p eval.post.0.group-weight=0.25

./dell2.sh -out /home/jorge/exps/EC/pred/nsga_e13_mix75 -p jobs=30 -p parent.0=build/classes/mase/app/pred/oneprey.params -p parent.1=build/classes/mase/novelty/nsga_ga.params -p parent.2=build/classes/mase/cooperative.params -p parent.3=build/classes/mase/gax.params -p pop.default-subpop.size=75 -p generations=500 -p pop.subpops=3 -p problem.escape-distance=13 -p fitness.novelty-index=2 -p eval.post.0.archive-mode=multiple -p eval.post.0.archive-size=2000 -p eval.post.0.archive-growth=0.025 -p eval.base.elite-mode=fitness -p eval.post.0=mase.novelty.GroupIndNoveltyEvaluation -p eval.post.0.group-behav-index=1 -p eval.post.0.group-weight=0.75

./dell2.sh -out /home/jorge/exps/EC/pred/nsf_e13_group -p jobs=30 -p parent.0=build/classes/mase/app/pred/oneprey.params -p parent.1=build/classes/mase/novelty/novelty.params -p parent.2=build/classes/mase/cooperative.params -p parent.3=build/classes/mase/gax.params -p pop.default-subpop.size=150 -p generations=500 -p pop.subpops=3 -p problem.escape-distance=13 -p eval.post.0.archive-size=2000 -p eval.post.0.archive-growth=0.025 -p eval.base.elite-mode=fitness

./dell2.sh -out /home/jorge/exps/EC/pred/nss_e13_group -p jobs=30 -p parent.0=build/classes/mase/app/pred/oneprey.params -p parent.1=build/classes/mase/novelty/novelty.params -p parent.2=build/classes/mase/cooperative.params -p parent.3=build/classes/mase/gax.params -p pop.default-subpop.size=150 -p generations=500 -p pop.subpops=3 -p problem.escape-distance=13 -p eval.post.0.archive-size=2000 -p eval.post.0.archive-growth=0.025 -p eval.base.elite-mode=score

