#!/bin/bash

./evolve.sh -out /home/jorge/exps/hybrid/herdfinal/s7_f2_p2_hyb_m100 -p jobs=20 -p current-job=10 -p parent.0=build/classes/mase/app/herding/herding_easy.params -p parent.1=build/classes/mase/spec/hybrid.params -p parent.2=build/classes/mase/cooperative.params -p parent.3=build/classes/mase/neat/neat.params -p pop.default-subpop.size=100 -p generations=10000 -p eval.base.max-evaluations=300000 -p exch.merge-threshold=1 -p exch.stability-time=10 -p exch.elite-portion=0.2 -p exch.homogeneous-start=false -p pop.subpops=7 -p problem.num-shepherds=7 -p problem.num-sheeps=2 -p problem.num-foxes=2 -p problem.smart-fox=false -p neat.INPUT.NODES=14

./evolve.sh -out /home/jorge/exps/hybrid/herdfinal/s7_f2_p2_hyb_m110 -p jobs=20 -p current-job=10 -p parent.0=build/classes/mase/app/herding/herding_easy.params -p parent.1=build/classes/mase/spec/hybrid.params -p parent.2=build/classes/mase/cooperative.params -p parent.3=build/classes/mase/neat/neat.params -p pop.default-subpop.size=100 -p generations=10000 -p eval.base.max-evaluations=300000 -p exch.merge-threshold=1.1 -p exch.stability-time=10 -p exch.elite-portion=0.2 -p exch.homogeneous-start=false -p pop.subpops=7 -p problem.num-shepherds=7 -p problem.num-sheeps=2 -p problem.num-foxes=2 -p problem.smart-fox=false -p neat.INPUT.NODES=14

./evolve.sh -out /home/jorge/exps/hybrid/herdfinal/s7_f2_p2_hyb_m125 -p jobs=20 -p current-job=10 -p parent.0=build/classes/mase/app/herding/herding_easy.params -p parent.1=build/classes/mase/spec/hybrid.params -p parent.2=build/classes/mase/cooperative.params -p parent.3=build/classes/mase/neat/neat.params -p pop.default-subpop.size=100 -p generations=10000 -p eval.base.max-evaluations=300000 -p exch.merge-threshold=1.25 -p exch.stability-time=10 -p exch.elite-portion=0.2 -p exch.homogeneous-start=false -p pop.subpops=7 -p problem.num-shepherds=7 -p problem.num-sheeps=2 -p problem.num-foxes=2 -p problem.smart-fox=false -p neat.INPUT.NODES=14

./evolve.sh -out /home/jorge/exps/hybrid/herdfinal/s7_f2_p2_hyb_m150 -p jobs=20 -p current-job=10 -p parent.0=build/classes/mase/app/herding/herding_easy.params -p parent.1=build/classes/mase/spec/hybrid.params -p parent.2=build/classes/mase/cooperative.params -p parent.3=build/classes/mase/neat/neat.params -p pop.default-subpop.size=100 -p generations=10000 -p eval.base.max-evaluations=300000 -p exch.merge-threshold=1.5 -p exch.stability-time=10 -p exch.elite-portion=0.2 -p exch.homogeneous-start=false -p pop.subpops=7 -p problem.num-shepherds=7 -p problem.num-sheeps=2 -p problem.num-foxes=2 -p problem.smart-fox=false -p neat.INPUT.NODES=14

./evolve.sh -out /home/jorge/exps/hybrid/herdfinal/s7_f2_p2_hyb_m175 -p jobs=20 -p current-job=10 -p parent.0=build/classes/mase/app/herding/herding_easy.params -p parent.1=build/classes/mase/spec/hybrid.params -p parent.2=build/classes/mase/cooperative.params -p parent.3=build/classes/mase/neat/neat.params -p pop.default-subpop.size=100 -p generations=10000 -p eval.base.max-evaluations=300000 -p exch.merge-threshold=1.75 -p exch.stability-time=10 -p exch.elite-portion=0.2 -p exch.homogeneous-start=false -p pop.subpops=7 -p problem.num-shepherds=7 -p problem.num-sheeps=2 -p problem.num-foxes=2 -p problem.smart-fox=false -p neat.INPUT.NODES=14



./evolve.sh -out /home/jorge/exps/hybrid/herdfinal/s7_f2_p2_hyb_t1 -p jobs=20 -p current-job=10 -p parent.0=build/classes/mase/app/herding/herding_easy.params -p parent.1=build/classes/mase/spec/hybrid.params -p parent.2=build/classes/mase/cooperative.params -p parent.3=build/classes/mase/neat/neat.params -p pop.default-subpop.size=100 -p generations=10000 -p eval.base.max-evaluations=300000 -p exch.merge-threshold=1.25 -p exch.stability-time=1 -p exch.elite-portion=0.2 -p exch.homogeneous-start=false -p pop.subpops=7 -p problem.num-shepherds=7 -p problem.num-sheeps=2 -p problem.num-foxes=2 -p problem.smart-fox=false -p neat.INPUT.NODES=14

./evolve.sh -out /home/jorge/exps/hybrid/herdfinal/s7_f2_p2_hyb_t5 -p jobs=20 -p current-job=10 -p parent.0=build/classes/mase/app/herding/herding_easy.params -p parent.1=build/classes/mase/spec/hybrid.params -p parent.2=build/classes/mase/cooperative.params -p parent.3=build/classes/mase/neat/neat.params -p pop.default-subpop.size=100 -p generations=10000 -p eval.base.max-evaluations=300000 -p exch.merge-threshold=1.25 -p exch.stability-time=5 -p exch.elite-portion=0.2 -p exch.homogeneous-start=false -p pop.subpops=7 -p problem.num-shepherds=7 -p problem.num-sheeps=2 -p problem.num-foxes=2 -p problem.smart-fox=false -p neat.INPUT.NODES=14

./evolve.sh -out /home/jorge/exps/hybrid/herdfinal/s7_f2_p2_hyb_t10 -p jobs=20 -p current-job=10 -p parent.0=build/classes/mase/app/herding/herding_easy.params -p parent.1=build/classes/mase/spec/hybrid.params -p parent.2=build/classes/mase/cooperative.params -p parent.3=build/classes/mase/neat/neat.params -p pop.default-subpop.size=100 -p generations=10000 -p eval.base.max-evaluations=300000 -p exch.merge-threshold=1.25 -p exch.stability-time=10 -p exch.elite-portion=0.2 -p exch.homogeneous-start=false -p pop.subpops=7 -p problem.num-shepherds=7 -p problem.num-sheeps=2 -p problem.num-foxes=2 -p problem.smart-fox=false -p neat.INPUT.NODES=14

./evolve.sh -out /home/jorge/exps/hybrid/herdfinal/s7_f2_p2_hyb_t15 -p jobs=20 -p current-job=10 -p parent.0=build/classes/mase/app/herding/herding_easy.params -p parent.1=build/classes/mase/spec/hybrid.params -p parent.2=build/classes/mase/cooperative.params -p parent.3=build/classes/mase/neat/neat.params -p pop.default-subpop.size=100 -p generations=10000 -p eval.base.max-evaluations=300000 -p exch.merge-threshold=1.25 -p exch.stability-time=15 -p exch.elite-portion=0.2 -p exch.homogeneous-start=false -p pop.subpops=7 -p problem.num-shepherds=7 -p problem.num-sheeps=2 -p problem.num-foxes=2 -p problem.smart-fox=false -p neat.INPUT.NODES=14

./evolve.sh -out /home/jorge/exps/hybrid/herdfinal/s7_f2_p2_hyb_t25 -p jobs=20 -p current-job=10 -p parent.0=build/classes/mase/app/herding/herding_easy.params -p parent.1=build/classes/mase/spec/hybrid.params -p parent.2=build/classes/mase/cooperative.params -p parent.3=build/classes/mase/neat/neat.params -p pop.default-subpop.size=100 -p generations=10000 -p eval.base.max-evaluations=300000 -p exch.merge-threshold=1.25 -p exch.stability-time=25 -p exch.elite-portion=0.2 -p exch.homogeneous-start=false -p pop.subpops=7 -p problem.num-shepherds=7 -p problem.num-sheeps=2 -p problem.num-foxes=2 -p problem.smart-fox=false -p neat.INPUT.NODES=14






./evolve.sh -out /home/jorge/exps/hybrid/herdfinal/s7_f2_p1_smart_hyb_m100 -p jobs=20 -p current-job=10 -p parent.0=build/classes/mase/app/herding/herding_easy.params -p parent.1=build/classes/mase/spec/hybrid.params -p parent.2=build/classes/mase/cooperative.params -p parent.3=build/classes/mase/neat/neat.params -p pop.default-subpop.size=100 -p generations=10000 -p eval.base.max-evaluations=300000 -p exch.merge-threshold=1.00 -p exch.stability-time=10 -p exch.elite-portion=0.2 -p exch.homogeneous-start=false -p pop.subpops=7 -p problem.num-shepherds=7 -p problem.num-sheeps=1 -p problem.num-foxes=2 -p problem.smart-fox=true -p neat.INPUT.NODES=12

./evolve.sh -out /home/jorge/exps/hybrid/herdfinal/s7_f2_p1_smart_hyb_m110 -p jobs=20 -p current-job=10 -p parent.0=build/classes/mase/app/herding/herding_easy.params -p parent.1=build/classes/mase/spec/hybrid.params -p parent.2=build/classes/mase/cooperative.params -p parent.3=build/classes/mase/neat/neat.params -p pop.default-subpop.size=100 -p generations=10000 -p eval.base.max-evaluations=300000 -p exch.merge-threshold=1.10 -p exch.stability-time=10 -p exch.elite-portion=0.2 -p exch.homogeneous-start=false -p pop.subpops=7 -p problem.num-shepherds=7 -p problem.num-sheeps=1 -p problem.num-foxes=2 -p problem.smart-fox=true -p neat.INPUT.NODES=12

./evolve.sh -out /home/jorge/exps/hybrid/herdfinal/s7_f2_p1_smart_hyb_m125 -p jobs=20 -p current-job=10 -p parent.0=build/classes/mase/app/herding/herding_easy.params -p parent.1=build/classes/mase/spec/hybrid.params -p parent.2=build/classes/mase/cooperative.params -p parent.3=build/classes/mase/neat/neat.params -p pop.default-subpop.size=100 -p generations=10000 -p eval.base.max-evaluations=300000 -p exch.merge-threshold=1.25 -p exch.stability-time=10 -p exch.elite-portion=0.2 -p exch.homogeneous-start=false -p pop.subpops=7 -p problem.num-shepherds=7 -p problem.num-sheeps=1 -p problem.num-foxes=2 -p problem.smart-fox=true -p neat.INPUT.NODES=12

./evolve.sh -out /home/jorge/exps/hybrid/herdfinal/s7_f2_p1_smart_hyb_m150 -p jobs=20 -p current-job=10 -p parent.0=build/classes/mase/app/herding/herding_easy.params -p parent.1=build/classes/mase/spec/hybrid.params -p parent.2=build/classes/mase/cooperative.params -p parent.3=build/classes/mase/neat/neat.params -p pop.default-subpop.size=100 -p generations=10000 -p eval.base.max-evaluations=300000 -p exch.merge-threshold=1.50 -p exch.stability-time=10 -p exch.elite-portion=0.2 -p exch.homogeneous-start=false -p pop.subpops=7 -p problem.num-shepherds=7 -p problem.num-sheeps=1 -p problem.num-foxes=2 -p problem.smart-fox=true -p neat.INPUT.NODES=12

./evolve.sh -out /home/jorge/exps/hybrid/herdfinal/s7_f2_p1_smart_hyb_m175 -p jobs=20 -p current-job=10 -p parent.0=build/classes/mase/app/herding/herding_easy.params -p parent.1=build/classes/mase/spec/hybrid.params -p parent.2=build/classes/mase/cooperative.params -p parent.3=build/classes/mase/neat/neat.params -p pop.default-subpop.size=100 -p generations=10000 -p eval.base.max-evaluations=300000 -p exch.merge-threshold=1.75 -p exch.stability-time=10 -p exch.elite-portion=0.2 -p exch.homogeneous-start=false -p pop.subpops=7 -p problem.num-shepherds=7 -p problem.num-sheeps=1 -p problem.num-foxes=2 -p problem.smart-fox=true -p neat.INPUT.NODES=12




./evolve.sh -out /home/jorge/exps/hybrid/herdfinal/s7_f2_p1_smart_hyb_t1 -p jobs=20 -p current-job=10 -p parent.0=build/classes/mase/app/herding/herding_easy.params -p parent.1=build/classes/mase/spec/hybrid.params -p parent.2=build/classes/mase/cooperative.params -p parent.3=build/classes/mase/neat/neat.params -p pop.default-subpop.size=100 -p generations=10000 -p eval.base.max-evaluations=300000 -p exch.merge-threshold=1.25 -p exch.stability-time=1 -p exch.elite-portion=0.2 -p exch.homogeneous-start=false -p pop.subpops=7 -p problem.num-shepherds=7 -p problem.num-sheeps=1 -p problem.num-foxes=2 -p problem.smart-fox=true -p neat.INPUT.NODES=12

./evolve.sh -out /home/jorge/exps/hybrid/herdfinal/s7_f2_p1_smart_hyb_t5 -p jobs=20 -p current-job=10 -p parent.0=build/classes/mase/app/herding/herding_easy.params -p parent.1=build/classes/mase/spec/hybrid.params -p parent.2=build/classes/mase/cooperative.params -p parent.3=build/classes/mase/neat/neat.params -p pop.default-subpop.size=100 -p generations=10000 -p eval.base.max-evaluations=300000 -p exch.merge-threshold=1.25 -p exch.stability-time=5 -p exch.elite-portion=0.2 -p exch.homogeneous-start=false -p pop.subpops=7 -p problem.num-shepherds=7 -p problem.num-sheeps=1 -p problem.num-foxes=2 -p problem.smart-fox=true -p neat.INPUT.NODES=12

./evolve.sh -out /home/jorge/exps/hybrid/herdfinal/s7_f2_p1_smart_hyb_t10 -p jobs=20 -p current-job=10 -p parent.0=build/classes/mase/app/herding/herding_easy.params -p parent.1=build/classes/mase/spec/hybrid.params -p parent.2=build/classes/mase/cooperative.params -p parent.3=build/classes/mase/neat/neat.params -p pop.default-subpop.size=100 -p generations=10000 -p eval.base.max-evaluations=300000 -p exch.merge-threshold=1.25 -p exch.stability-time=10 -p exch.elite-portion=0.2 -p exch.homogeneous-start=false -p pop.subpops=7 -p problem.num-shepherds=7 -p problem.num-sheeps=1 -p problem.num-foxes=2 -p problem.smart-fox=true -p neat.INPUT.NODES=12

./evolve.sh -out /home/jorge/exps/hybrid/herdfinal/s7_f2_p1_smart_hyb_t15 -p jobs=20 -p current-job=10 -p parent.0=build/classes/mase/app/herding/herding_easy.params -p parent.1=build/classes/mase/spec/hybrid.params -p parent.2=build/classes/mase/cooperative.params -p parent.3=build/classes/mase/neat/neat.params -p pop.default-subpop.size=100 -p generations=10000 -p eval.base.max-evaluations=300000 -p exch.merge-threshold=1.25 -p exch.stability-time=15 -p exch.elite-portion=0.2 -p exch.homogeneous-start=false -p pop.subpops=7 -p problem.num-shepherds=7 -p problem.num-sheeps=1 -p problem.num-foxes=2 -p problem.smart-fox=true -p neat.INPUT.NODES=12

./evolve.sh -out /home/jorge/exps/hybrid/herdfinal/s7_f2_p1_smart_hyb_t25 -p jobs=20 -p current-job=10 -p parent.0=build/classes/mase/app/herding/herding_easy.params -p parent.1=build/classes/mase/spec/hybrid.params -p parent.2=build/classes/mase/cooperative.params -p parent.3=build/classes/mase/neat/neat.params -p pop.default-subpop.size=100 -p generations=10000 -p eval.base.max-evaluations=300000 -p exch.merge-threshold=1.25 -p exch.stability-time=25 -p exch.elite-portion=0.2 -p exch.homogeneous-start=false -p pop.subpops=7 -p problem.num-shepherds=7 -p problem.num-sheeps=1 -p problem.num-foxes=2 -p problem.smart-fox=true -p neat.INPUT.NODES=12

