#!/bin/bash
CLASSPATH="build/classes:lib/*:../jbotevolver/JBotSim/build/classes:../jbotevolver/JBotEvolver/build/classes:../drones/JBotAquatic/build/classes:../drones/CommonInterface/build/classes:../jbotevolver/JBotSim/BaseClient.jar:../drones/Behaviors/build/classes:../drones/CommonInterface/lib/*"

