#!/bin/bash
CLASSPATH="build/classes:lib/*:dependencies/ECJ/dist/ECJ.jar:dependencies/MASON/dist/MASON.jar:dependencies/NEAT4J/dist/NEAT4J.jar:../jbotevolver/JBotSim/dist/JBotSim.jar:../jbotevolver/JBotEvolver/dist/JBotEvolver.jar:../drones/JBotAquatic/dist/JBotAquatic.jar:../drones/CommonInterface/dist/CommonInterface.jar:../drones/Behaviors/dist/Behaviors.jar:../jbotevolver/JBotSim/BaseClient.jar:../jbotevolver/JBotSim/asm-all-4.0.jar:../drones/CommonInterface/lib/*"

